export default function ReplacementPolicy() {
  return (
      <div className="min-h-screen bg-white dark:bg-[hsl(var(--background))] text-slate-900 dark:text-[hsl(var(--foreground))]">
            <div className="bg-[#0f2318] px-6 py-16 text-center">
                    <p className="text-xs tracking-[0.2em] text-green-400 font-semibold mb-3">POLICIES</p>
                            <h1 className="text-4xl font-bold text-white">Replacement Policy</h1>
                                  </div>
                                        <div className="max-w-3xl mx-auto px-6 py-14 space-y-8 text-gray-600 dark:text-[hsl(var(--muted-foreground))] text-sm leading-relaxed">
                                                <section>
                                                          <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Eligible for Replacement</h2>
                                                                    <p>We offer replacements for products that are:</p>
                                                                              <ul className="list-disc ml-5 mt-2 space-y-1">
                                                                                          <li>Damaged or broken on delivery</li>
                                                                                                      <li>Incorrect item shipped</li>
                                                                                                                  <li>Significantly different from the product description</li>
                                                                                                                            </ul>
                                                                                                                                    </section>
                                                                                                                                            <section>
                                                                                                                                                      <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">How to Request a Replacement</h2>
                                                                                                                                                                <p>Raise a replacement request within <strong>48 hours of delivery</strong>. Share your order ID, photos of the item received, and a brief description of the issue to <a href="mailto:info@hadly.live" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">info@hadly.live</a> or WhatsApp us at <a href="tel:+919019053878" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">+91 90190 53878</a>.</p>
                                                                                                                                                                        </section>
                                                                                                                                                                                <section>
                                                                                                                                                                                          <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Replacement Timeline</h2>
                                                                                                                                                                                                    <p>Approved replacements are dispatched within <strong>3–5 business days</strong> after verification.</p>
                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                    <section>
                                                                                                                                                                                                                              <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Non-Eligible Items</h2>
                                                                                                                                                                                                                                        <ul className="list-disc ml-5 space-y-1">
                                                                                                                                                                                                                                                    <li>Products with visible user damage or misuse</li>
                                                                                                                                                                                                                                                                <li>Requests raised after 48 hours of delivery</li>
                                                                                                                                                                                                                                                                            <li>Items purchased during clearance or final sales</li>
                                                                                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                      <p className="text-xs text-gray-400 dark:text-[hsl(var(--muted-foreground))] border-t border-gray-100 dark:border-[hsl(var(--border))] pt-6">Last updated: March 2026  HADLY, Bangalore, India</p>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                  