export default function ShippingPolicy() {
  return (
      <div className="min-h-screen bg-white dark:bg-[hsl(var(--background))] text-slate-900 dark:text-[hsl(var(--foreground))]">
            <div className="bg-[#0f2318] px-6 py-16 text-center">
                    <p className="text-xs tracking-[0.2em] text-green-400 font-semibold mb-3">POLICIES</p>
                            <h1 className="text-4xl font-bold text-white">Shipping Policy</h1>
                                  </div>
                                        <div className="max-w-3xl mx-auto px-6 py-14 space-y-8 text-gray-600 dark:text-[hsl(var(--muted-foreground))] text-sm leading-relaxed">
                                                <section>
                                                          <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Delivery Timelines</h2>
                                                                    <ul className="list-disc ml-5 space-y-1">
                                                                                <li><strong>Metro cities</strong> (Bangalore, Mumbai, Delhi, Chennai, Hyderabad): 2–4 business days</li>
                                                                                            <li><strong>Tier 2 & Tier 3 cities</strong>: 4–7 business days</li>
                                                                                                        <li><strong>Rural & remote areas</strong>: 7–10 business days</li>
                                                                                                                  </ul>
                                                                                                                          </section>
                                                                                                                                  <section>
                                                                                                                                            <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Shipping Charges</h2>
                                                                                                                                                      <p><strong>Free shipping</strong> on all orders above ₹799. A flat shipping fee of ₹49 is applicable on orders below ₹799.</p>
                                                                                                                                                              </section>
                                                                                                                                                                      <section>
                                                                                                                                                                                <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Order Processing</h2>
                                                                                                                                                                                          <p>Orders are processed within <strong>1–2 business days</strong> of payment confirmation. You will receive a tracking link via SMS/email once dispatched.</p>
                                                                                                                                                                                                  </section>
                                                                                                                                                                                                          <section>
                                                                                                                                                                                                                    <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Tracking Your Order</h2>
                                                                                                                                                                                                                              <p>A tracking ID will be shared after dispatch. You can track your order via the courier partner's website or contact us at <a href="mailto:info@hadly.live" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">info@hadly.live</a>.</p>
                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                              <section>
                                                                                                                                                                                                                                                        <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Packaging</h2>
                                                                                                                                                                                                                                                                  <p>All HADLY products are securely packed to prevent damage in transit. We use minimal, eco-friendly packaging wherever possible.</p>
                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                  <p className="text-xs text-gray-400 dark:text-[hsl(var(--muted-foreground))] border-t border-gray-100 dark:border-[hsl(var(--border))] pt-6">Last updated: March 2026  HADLY, Bangalore, India</p>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                              