export default function RefundPolicy() {
  return (
      <div className="min-h-screen bg-white dark:bg-[hsl(var(--background))] text-slate-900 dark:text-[hsl(var(--foreground))]">
            <div className="bg-[#0f2318] px-6 py-16 text-center">
                    <p className="text-xs tracking-[0.2em] text-green-400 font-semibold mb-3">POLICIES</p>
                            <h1 className="text-4xl font-bold text-white">Refund Policy</h1>
                                  </div>
                                        <div className="max-w-3xl mx-auto px-6 py-14 space-y-8 text-gray-600 dark:text-[hsl(var(--muted-foreground))] text-sm leading-relaxed">
                                                <section>
                                                          <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Refund Eligibility</h2>
                                                                    <p>Refunds are issued in the following cases:</p>
                                                                              <ul className="list-disc ml-5 mt-2 space-y-1">
                                                                                          <li>Order cancelled within 24 hours before dispatch</li>
                                                                                                      <li>Product not delivered within the estimated delivery window</li>
                                                                                                                  <li>Replacement not possible due to stock unavailability</li>
                                                                                                                              <li>Duplicate payment charged</li>
                                                                                                                                        </ul>
                                                                                                                                                </section>
                                                                                                                                                        <section>
                                                                                                                                                                  <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Refund Process</h2>
                                                                                                                                                                            <p>Once your refund request is approved, the amount will be credited back to your original payment method within <strong>5–7 business days</strong>. UPI and wallet refunds may reflect sooner.</p>
                                                                                                                                                                                    </section>
                                                                                                                                                                                            <section>
                                                                                                                                                                                                      <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">How to Raise a Refund Request</h2>
                                                                                                                                                                                                                <p>Email us at <a href="mailto:info@hadly.live" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">info@hadly.live</a> with your order ID and reason, or call <a href="tel:+919019053878" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">+91 90190 53878</a>.</p>
                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                <section>
                                                                                                                                                                                                                                          <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Non-Refundable Cases</h2>
                                                                                                                                                                                                                                                    <ul className="list-disc ml-5 space-y-1">
                                                                                                                                                                                                                                                                <li>Change of mind after dispatch</li>
                                                                                                                                                                                                                                                                            <li>Incorrect shipping address provided by customer</li>
                                                                                                                                                                                                                                                                                        <li>Product used or opened (except quality issues)</li>
                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-gray-400 dark:text-[hsl(var(--muted-foreground))] border-t border-gray-100 dark:border-[hsl(var(--border))] pt-6">Last updated: March 2026  HADLY, Bangalore, India</p>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                              