export default function CancellationPolicy() {
  return (
      <div className="min-h-screen bg-white dark:bg-[hsl(var(--background))]">
            <div className="bg-[#0f2318] px-6 py-16 text-center">
                    <p className="text-xs tracking-[0.2em] text-green-400 font-semibold mb-3">POLICIES</p>
                            <h1 className="text-4xl font-bold text-white">Cancellation Policy</h1>
                                  </div>
                                        <div className="max-w-3xl mx-auto px-6 py-14 prose prose-sm dark:prose-invert text-gray-600 dark:text-[hsl(var(--muted-foreground))] space-y-8">
                                                <section>
                                                          <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Order Cancellation</h2>
                                                                    <p>
                                                                                You may cancel your order within <strong>24 hours of placing it</strong>, provided the order has not yet been dispatched. To cancel, please contact us at <a href="mailto:info@hadly.live" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">info@hadly.live</a> or call <a href="tel:+919019053878" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">+91 90190 53878</a> with your order details.
                                                                                          </p>
                                                                                                  </section>
                                                                                                          <section>
                                                                                                                    <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Post-Dispatch Cancellations</h2>
                                                                                                                              <p>
                                                                                                                                          Once an order has been dispatched, it cannot be cancelled. You may initiate a return or replacement after receiving the product as per our Replacement Policy.
                                                                                                                                                    </p>
                                                                                                                                                            </section>
                                                                                                                                                                    <section>
                                                                                                                                                                              <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Cancellation by HADLY</h2>
                                                                                                                                                                                        <p>
                                                                                                                                                                                                    HADLY reserves the right to cancel orders in cases of stock unavailability, payment issues, or incorrect pricing. In such cases, a full refund will be issued within 5–7 business days.
                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                              <section>
                                                                                                                                                                                                                                        <h2 className="text-lg font-bold text-gray-800 dark:text-[hsl(var(--foreground))] mb-3">Contact Us</h2>
                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                              For any cancellation-related queries, reach us at <a href="mailto:info@hadly.live" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">info@hadly.live</a> or <a href="tel:+919019053878" className="text-[#1a3a2a] dark:text-emerald-300 font-medium">+91 90190 53878</a>.
                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                        <p className="text-xs text-gray-400 dark:text-[hsl(var(--muted-foreground))] border-t border-gray-100 dark:border-[hsl(var(--border))] pt-6">
                                                                                                                                                                                                                                                                                                  Last updated: March 2026  HADLY, Bangalore, India
                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                      